# Generated by Django 5.2.6 on 2025-09-28 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_latitude', models.FloatField(help_text='Latitudine target (-90 a 90)', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('target_longitude', models.FloatField(help_text='Longitudine target (-180 a 180)', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('activation_distance', models.FloatField(default=10.0, help_text='Distanza in metri per attivazione AR', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('character_image', models.ImageField(blank=True, help_text='Immagine del personaggio (PNG)', null=True, upload_to='characters/')),
            ],
        ),
    ]
