# Generated by Django 5.2.7 on 2025-10-18 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charconfiguration',
            name='altitude',
            field=models.FloatField(default=0.0, help_text='Altitudine in metri sul livello del mare'),
        ),
        migrations.AddField(
            model_name='charconfiguration',
            name='base_size',
            field=models.FloatField(default=1.0, help_text='Scala del personaggio (1.0 = normale, 2.0 = doppio)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='charconfiguration',
            name='display_mode',
            field=models.CharField(choices=[('standing', 'In piedi a terra'), ('floating', 'Fluttuante'), ('wall', 'Appeso a muro')], default='standing', help_text='Modalità di visualizzazione del personaggio', max_length=20),
        ),
        migrations.AddField(
            model_name='charconfiguration',
            name='facing_direction',
            field=models.FloatField(default=0.0, help_text='Direzione verso cui guarda il personaggio in gradi (0=Nord, 90=Est, 180=Sud, 270=Ovest)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AddField(
            model_name='charconfiguration',
            name='height_offset',
            field=models.FloatField(default=0.0, help_text='Altezza dal suolo in metri (es: 1.7 per persona in piedi, 0 per oggetto a terra)', validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
