# Generated by Django 5.2.7 on 2025-10-18 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_charconfiguration_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charconfiguration',
            name='marker_image',
            field=models.ImageField(blank=True, help_text='Immagine marker da stampare/mostrare (JPG/PNG)', null=True, upload_to='markers/'),
        ),
        migrations.AddField(
            model_name='charconfiguration',
            name='marker_offset_x',
            field=models.FloatField(default=0.0, help_text='Offset orizzontale dal marker in metri (positivo = destra)', validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='charconfiguration',
            name='marker_offset_y',
            field=models.FloatField(default=0.0, help_text='Offset verticale dal marker in metri (positivo = su)', validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='charconfiguration',
            name='marker_offset_z',
            field=models.FloatField(default=0.5, help_text='Offset profondità dal marker in metri (positivo = avanti)', validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='charconfiguration',
            name='use_marker',
            field=models.BooleanField(default=False, help_text='Usa marker di riferimento per posizionamento preciso'),
        ),
    ]
