# Generated by Django 5.2.7 on 2025-10-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_charconfiguration_marker_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charconfiguration',
            name='positioning_marker_image',
            field=models.ImageField(blank=True, help_text='Immagine marker per positioning (decide DOVE posizionare il character - opzionale)', null=True, upload_to='markers/'),
        ),
        migrations.AlterField(
            model_name='charconfiguration',
            name='marker_image',
            field=models.ImageField(blank=True, help_text='Immagine marker per detection (decide SE mostrare il character)', null=True, upload_to='markers/'),
        ),
    ]
