# Generated by Django 5.2.7 on 2026-01-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_charconfiguration_positioning_marker_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charconfiguration',
            name='detection_marker_features',
            field=models.IntegerField(default=0, help_text='Numero di features ORB estratti dal detection marker (calcolato automaticamente)'),
        ),
        migrations.AddField(
            model_name='charconfiguration',
            name='positioning_marker_features',
            field=models.IntegerField(default=0, help_text='Numero di features ORB estratti dal positioning marker (calcolato automaticamente)'),
        ),
    ]
