# Generated by Django 5.2.7 on 2026-01-21 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_charconfiguration_detection_marker_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charconfiguration',
            name='use_yolo_detection',
            field=models.BooleanField(default=False, help_text='Usa YOLO per rilevare oggetti invece di marker immagine'),
        ),
        migrations.AddField(
            model_name='charconfiguration',
            name='yolo_confidence_threshold',
            field=models.FloatField(default=0.5, help_text='Soglia di confidenza minima per detection YOLO (0.5 = 50%)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='charconfiguration',
            name='yolo_object_class',
            field=models.CharField(blank=True, help_text="Classe oggetto da rilevare (es: 'bottle', 'chair', 'laptop') - Lista completa: person, bicycle, car, motorcycle, airplane, bus, train, truck, boat, traffic light, fire hydrant, stop sign, parking meter, bench, bird, cat, dog, horse, sheep, cow, elephant, bear, zebra, giraffe, backpack, umbrella, handbag, tie, suitcase, frisbee, skis, snowboard, sports ball, kite, baseball bat, baseball glove, skateboard, surfboard, tennis racket, bottle, wine glass, cup, fork, knife, spoon, bowl, banana, apple, sandwich, orange, broccoli, carrot, hot dog, pizza, donut, cake, chair, couch, potted plant, bed, dining table, toilet, tv, laptop, mouse, remote, keyboard, cell phone, microwave, oven, toaster, sink, refrigerator, book, clock, vase, scissors, teddy bear, hair drier, toothbrush", max_length=50, null=True),
        ),
    ]
