# Generated by Django 5.2.7 on 2026-01-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_charconfiguration_use_yolo_detection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charconfiguration',
            name='yolo_object_class',
            field=models.CharField(blank=True, help_text='Classe oggetto FISSO da rilevare nei negozi/spazi urbani. Oggetti statici consigliati: chair (sedia), couch (divano), potted plant (pianta), dining table (tavolo), bench (panchina), tv (televisore), laptop, clock (orologio), vase (vaso), book (libro), bottle (bottiglia display), wine glass (bicchiere), cup (tazza), refrigerator (frigo), microwave, oven (forno), toaster, sink (lavandino), toilet, bed (letto), desk, monitor. EVITA: person, car, bicycle e oggetti mobili.', max_length=50, null=True),
        ),
    ]
